### ISSUE TITLE
ContentDialog does not show when another application is full screen

### ISSUE THREAD

**Issue by nlogozzo** [amwx/FluentAvalonia#102]
I have an application that shows a `ContentDialog` when the application starts. However, when I have an application in the background that is fullscreen, i was running Serato DJ Pro, but it could be replicated with a game that is fullscreen, then the `ContentDialog` is not shown and the application freezes until I close the fullscreen application in which then the `ContentDialog` would be shown.

**Comment by amwx** [comment]
How exactly are you launching the dialog when the app starts? Since ContentDialog requires a window, that window needs to be fully initialized and visible first. I'm guessing, you're launching it too early causing the thread to hold awaiting the dialog result - and the window is getting lost behind the full screen app - since it hasn't been fully registered with the system yet. That's my guess without knowing more. If so, either wait for the window to fully load, or launch the dialog synchronously.

**Comment by nlogozzo** [comment]
The dialog is shown in the `Opened` event of the window. Let me see if I can produce a video to show it better

**Comment by nlogozzo** [comment]
Hmm...I can't seem to reproduce it now. Seems to have been an issue with a library I was using who's async methods weren't truly async. I updated the library and the issue seems to be gone 🤷
