### ISSUE TITLE
Menu Animation

### ISSUE THREAD

**Issue by nlogozzo** [amwx/FluentAvalonia#103]
WinUI apps such as Paint and Notepad on Windows 11, have a draw sliding animation that reveals menu items when a top-level menu item is clicked. Can we see this animation in this library or is there a way to replicate it?

**Comment by amwx** [comment]
I'd love to implement popup animations and shadows, but its a very difficult task to do.

1- It requires the platform supports transparency. True on Windows and Mac (I think), but not all linux distros. Why? What actually gets animated is the root element (probably a `Border`) thus the top-level HWND/window need to be completely transparent for the effect to properly take. You could get around this if you know/check if the platform supports transparency and just disable the effects there.

2- It removes the ability to use Acrylic background popups. The way we get acrylic (and Mica) effects now is essentially a hack tying into Window UI Compositor. A window is created an initialized into WinUI's composition tree, and the Avalonia render surface is passed in as WinUI visual, which is then composited by WinUI. Thus if you set a popup (or any window) to use blur, the window is blurred - and you no longer have a transparent host for the popup content and the animation effect is degraded.
The only way to get around this is to either, A) disable the effect if blurring popups are used (which isn't ideal nor something I'd want to do), or B) somehow wrap the WinUI Compositor's HostBackdropBrush into a Skia texture - but I don't even think that's possible.

3- To be completely effective, it really should be implemented upstream in Avalonia as part of the popup positioning and opening code - because the animations need to know where the popup is opening and in which direction - especially if you configured it to open down, but there's not enough space so it opens above the PlacementTarget - the animation needs to reverse. This is doable outside of the main Popup code, but requires some hacks as the content isn't added to the tree until the popup opens, so you have to intercept that, find the root (either PopupRoot or OverlayPopupHost), hide the content, determine how the popup is opening, run the correct animation, and then display as normal. 
Shadows are even more complicated...

Sorry for the long response. This is definitely something I'd love to do as the animations and shadows are a key part of the Fluent design system. I've experimented before, but like I said, it's not straightforward - at least not when you're maintaining a x-plat control library

**Comment by cricketthomas** [comment]
I wonder if anything has changed since the v11 release to support box shadows. 
Would it be too much of a hack to just check for the platform you're on when rendering them? I was playing around with trying to add some to MenuStyles.xaml
