### ISSUE TITLE
Weird border when using CoreWindow

### ISSUE THREAD

**Issue by alex6dj** [amwx/FluentAvalonia#122]
**Describe the bug**
When using `CoreWindow` a white border of 1px appears around the window, but only when the app window get focus. When the app window lost focus (another window is selected) the `CoreWindow` looks like the normal `Window`.

**Screenshots**

![Captura de pantalla (143)](https://user-images.githubusercontent.com/27690651/160258906-9f8fc597-f565-4dbd-acac-f622adeea1e3.png)
*CoreWindow with focus*

![Captura de pantalla (144)](https://user-images.githubusercontent.com/27690651/160258913-ef8a232a-a326-451c-97c9-089af92c707c.png)
*CoreWindow without focus*

![Captura de pantalla (145)](https://user-images.githubusercontent.com/27690651/160258920-b839ea0f-11aa-4a45-87fd-6138b7450e49.png)
*Using Window*

**Desktop/Platform (please complete the following information):**
 - OS: Windows 10
 - FluentAvalonia Version 1.3.2
 - Avalonia Version 0.10.13

**Additional context**

**Comment by amwx** [comment]
The white is the normal Win32 window system border. Something broke in Windows 10 with extended frame window styles that was never fixed that makes this a nightmare to deal with.

Basically, for `CoreWindow` to behave properly the system border has to show. But for some reason when `WS_EX_NOREDIRECTIONBITMAP` is specified as an extended window style, on Windows 10 the top border of the window is hidden. The left/right/bottom still exist though ??, and they're white because you don't have "Show accent color on Titlebars" enabled in Windows settings. To still have a border at the top I fake it on Win 10 by using the system accent color - which of course fails in a case like this. Unfortunately its not an easy solution to fix:
1 - I can attempt to read the system setting and not use the accent color. This is the easier option, but still has challenges like how to get that setting (it has to be a reliable API, and NOT the registry), and two ensuring the colors still match the actual window border colors for light/dark/high contrast or this issue technically still persists.

2- The proper fix for this is to do what Windows Terminal does, and use a parent window and host the actual xaml window inside it. However, that requires completely re-writing the Win32 window infrastructure since the Avalonia window would no longer be top level, but a child window. That's incredibly difficult, and depending on whether some of the needed infrastructure is private to Avalonia assemblies, may be impossible to do.

**Comment by alex6dj** [comment]
Ok, really good answer again. Already check, and you are right, work great in Win11 so it is a Win10 thing. No problem with that, it will lost support anytime soon :wink:. Closing now.
