### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by xingxing21** [amwx/FluentAvalonia#128]
Hi, Everyone
I built this project on macOS 10.15 after I disabled the things related to the Windows Interop.
The building and running are good but the vertical alignment of the text in all the controls is strange.

![image](https://user-images.githubusercontent.com/39619359/162418157-c7e9283e-6cb8-42c8-abca-e9cc0ae6b56c.png)

Does not the styling of this support on macOS?
Or how to fix it?

Thank!

**Comment by amwx** [comment]
So, it's an issue with taking the Fluent theme and making it cross-platform. Microsoft designs the controls specifically for using the Segoe UI or Segoe UI Variable font which isn't available except on Windows (unless you install yourself). Many of the controls position text top/left and then use Margins to make them appear centered - which when Segoe UI isn't the font, becomes a huge issue, as you pointed out. I can't ship this library with those fonts for licensing reasons, and would really rather not ship a full font either. 

I'm still trying to figure out the best solution, and I may end up just removing the margins and setting VerticalAlignment to Center to try and avoid these issues. It breaks with the Fluent theme, but it might just be the x-plat way to handle this...

**Comment by robloo** [comment]
Note that the top/left margins for positioning in WinUI are done for multi-line text. This allows the actual checkbox, for example, to appear next to the first line instead of centered between two (which looks worse).

There is no general-purpose way to "center with first line of text" in any XAML frameworks. Therefore vertical centering is probably the best that can be done right now. Some advanced TextFormatting measurements would otherwise have to be supported in XAML.

**Comment by robloo** [comment]
I had a better idea on how to fix this without loosing functionality.

Create two resources for TopLeftMargin and VerticalAlignment. These would be shared and used in the radiobutton and checkbox, etc. They would provide the positioning info to center within the first line of text using a margin. Or, just change the vertical alignment to center.
