### ISSUE TITLE
Border edges of flyouts and menus are not transparent on Linux

### ISSUE THREAD

**Issue by ThePBone** [amwx/FluentAvalonia#133]
**Describe the bug**
The edges of flyouts, menus, tooltips, and any kind of popups are not transparent outside their rounded border. They appear to be rectangular instead; see screenshots below.

**Screenshots**
Example flyout in the included sample application:
![image](https://user-images.githubusercontent.com/38386967/163735048-8d19e0aa-1c55-47a2-a768-9071569dbe96.png)
It's easier to recognize the corners in dark or high-contrast mode:
![image](https://user-images.githubusercontent.com/38386967/163735074-2c658d4e-b3ec-42b4-ae32-53844320ad53.png)

A regular Avalonia flyout (from Avalonia's control sample) behaves normally:
![image](https://user-images.githubusercontent.com/38386967/163735387-1630db42-283e-4b2f-bfca-853bd2d473ce.png)

**Desktop/Platform:**
 - OS: Linux 5.15.34-1-lts / EndeavourOS (Arch-based)
 - FluentAvalonia Version: latest commit (fccd2716276d5bf5f22fea0dd8e4b695ba3c2c44) built from source
 - Avalonia Version: 0.10.13

**Comment by amwx** [comment]
If this is just occurring in the sample app, then it's because I have popup windows using Acrylic blur. It looks like your linux distro supports blurred windows, and that's why you're seeing the rectangular region. This isn't forced anywhere except the sample app, creating popups in external projects should work normally.

I hadn't noticed this because A) on Windows there's an option to round the actual window, and B) I test on linux via WSL, which doesn't support blur and defaults to just transparent. I've made a note of this though, will either turn it off in the sample app or see if I can enable it selectively.
