### ISSUE TITLE
PickerFlyoutBase: ShouldShowConfirmationButtons has no effect

### ISSUE THREAD

**Issue by ThePBone** [amwx/FluentAvalonia#137]
**Describe the bug**
Hey, I'm implementing a custom flyout picker that derives from `PickerFlyoutBase`. I wanted to hide optionally the confirm/cancel buttons (like the ColorPickerFlyout can). 

I noticed that `PickerFlyoutBase` has a virtual function that determines whether the buttons should be visible: `protected virtual bool ShouldShowConfirmationButtons()`. However, overriding it with a method that returns a custom boolean value had no effect.

It seems that this virtual method is ignored and is only handled in the ColorPickerFlyout class:
![image](https://user-images.githubusercontent.com/38386967/166127924-6bd1f01e-4146-4767-8129-57f5281a83fb.png)

So I thought I could just work around this by copying the code in the ColorPickerFlyout class that takes care of toggling the visibility of the confirmation buttons.
```c#
(Popup.Child as PickerFlyoutPresenter).ShowHideButtons(ShouldShowConfirmationButtons());
```
Unfortunately, `PickerFlyoutPresenter.ShowHideButtons` has an internal access modifier, so it is inaccessible for me without directly modifying the source code of FluentAvalonia.

Would it be possible to handle `ShouldShowConfirmationButtons` globally instead of only in `ColorPickerFlyout`, or alternatively, expose the `ShowHideButtons` method publicly?

**Desktop/Platform:**
 - OS: Linux
 - FluentAvalonia Version: latest
 - Avalonia Version: 0.10.13

**Comment by amwx** [comment]
That's definitely a bug. I think I need to make `PickerFlyoutPresenter` know about its owning Flyout so it can properly query `ShouldShowConfirmationButtons()` rather than what I have now.

I'm not sure when I'll get around to fixing this (and this fix technically is a breaking change so it may not be until 2.0/when Avalonia releases 11.0). In the mean time, you can copy the `PickerFlyoutPresenter` to your project to give you control. To prevent needing to re-do the template, you can implement `IStyleable` and add `Type IStyleable.StyleKey => typeof(PickerFlyoutPresenter);` to using the existing template. It's not ideal, but may be a good short term solution that isn't reflection.
