### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by robloo** [amwx/FluentAvalonia#14]
So first, awesome work @amwx!! It's great to see someone take this up and it's sorely needed for those of us committed to WinUI but looking at Avalonia for future ports (it's the most stable macOS/Linux desktop option on the market).

I know the Avalonia Core team has reached out to you but wonder if you can share the strategy for this library? As I see it several of these core controls should end up in Avalonia UI itself (perhaps not with the latest styles). This project would still likely be needed to:

 1. Include the controls not deemed worthy of inclusion in Avalonia itself (RatingControl, etc.)
 2. Include the Fluent version 1 and 2 styles for ALL controls. It is likely that Avalonia will deviate and use custom styling so being able to restyle to Fluent using this lib is very useful.
 3. This library could still mirror WinUI with all controls and just keep everything synced with WinUI as Avalonia might deviate in the future.

Controls that are prime candidates for Avalonia inclusion in my option are:
 * ColorPicker (however I plan a port that is closer to WinUI + UWP Community Toolkit)
 * SplitButton/ToggleSplitButton/DropDownButton
 * NavigationView
 * ContentDialog
 * All the various Icons (which @maxkatz6 is already working on I believe). Have you discussed code sharing I wonder?

For the buttons (SplitButton/ToggleSplitButton, etc.) I was planning to port those over myself. However, you have done the vast majority of the work including Flyouts, awesome! Do you have any concerns if I use your code and try to get these into Avalonia itself? Obviously, I'll need to adjust the styles, but most of the code-behind will likely be copy-pasted verbatim. I would only double check with latest WinUI.

**Comment by amwx** [comment]
> I know the Avalonia Core team has reached out to you but wonder if you can share the strategy for this library?

To be honest, I don't really have a defined strategy. Most of what I've ported so far has been just as a challenge to myself. Of course, now that this is public, if something is requested I will definitely look into it. WinUI somewhat limits me ATM b/c not everything is open source, which means either reverse engineer it (which I've done...Flyouts, SplitView, ContentDialog, for example, but isn't ideal) or wait until MS finally decides to release their code. I will say...I'll do what I can, but I'm not interested in maintaining a 1:1 port of WinUI for Avalonia, that would be a significant amount of work and maintenance need that I'm not up to for a side/hobby project.

 >As I see it several of these core controls should end up in Avalonia UI itself (perhaps not with the latest styles). This project would still likely be needed to:
> 
>     1. Include the controls not deemed worthy of inclusion in Avalonia itself (RatingControl, etc.)
> 
>     2. Include the Fluent version 1 and 2 styles for ALL controls. It is likely that Avalonia will deviate and use custom styling so being able to restyle to Fluent using this lib is very useful.
> 
>     3. This library could still mirror WinUI with all controls and just keep everything synced with WinUI as Avalonia might deviate in the future.

For the new controls my library offers, I have made them compatible with the base Fluent theme in Avalonia, so while the default is to use the new WinUI styles, you don't have to. The templates are unchanged from the new WinUI styles but the brushes/colors have been remapped. In most cases, there really is no difference between the templates.

> Controls that are prime candidates for Avalonia inclusion in my option are:
> 
>     * ColorPicker (however I plan a port that is closer to WinUI + UWP Community Toolkit)
> 
>     * SplitButton/ToggleSplitButton/DropDownButton
> 
>     * NavigationView
> 
>     * ContentDialog
> 
>     * All the various Icons (which @maxkatz6 is already working on I believe). Have you discussed code sharing I wonder?

Personally (and everyone is going to see this different), I think ColorPicker is best left to 3rd party libs. Not everyone needs one, and there are many different styles that this control can take (WinUI version, WinUI Com. Toolkit, my version, every other colorpicker in existence). The NavigationView is being discussed. There are some things I need to look into before this can be moved though, which I haven't had the chance to do yet. I'll agree Avalonia probably needs some sort of Dialog implementation built in, but more complex things like ContentDialog are probably best left to 3rd parties. 

TBH, I haven't really looked much at the Icon implementation in Avalonia, mostly because I have my own. The biggest difference I see, is I decided to let the icons draw themselves, rather than make them like WinUI where elements (TextBlock, Path, etc.) are injected into the tree. I also have a SymbolIcon that uses the font files from the Fluent Icons repo. The biggest downside there is the need to host the 2 font files in assembly (atm are ~1.5MB), which also need to be periodically updated.

> For the buttons (SplitButton/ToggleSplitButton, etc.) I was planning to port those over myself. However, you have done the vast majority of the work including Flyouts, awesome! Do you have any concerns if I use your code and try to get these into Avalonia itself? Obviously, I'll need to adjust the styles, but most of the code-behind will likely be copy-pasted verbatim. I would only double check with latest WinUI.

Go for it. Split/ToggleSplit Button I did use some custom internal stuff to implement this. Basically I have a very basic VisualStateManager to help with switching all the different states (this is one area where the CSS style styling in Avalonia doesn't work as nicely). You'll have to remove that, but otherwise feel free to use it as a starting point.
DropDownButton doesn't actually have any code logic (in WinUI it's all just UIA stuff), so I'm not really sure if this adds any real value b/c Button already has a Flyout property. Regardless, I really think Menus need to be overhauled first, as discussed in the Flyout PR. The archaic WPF way feels clunky with MenuFlyouts.

**Comment by robloo** [comment]
> To be honest, I don't really have a defined strategy. Most of what I've ported so far has been just as a challenge to myself. Of course, now that this is public, if something is requested I will definitely look into it... I'm not interested in maintaining a 1:1 port of WinUI for Avalonia, that would be a significant amount of work and maintenance need that I'm not up to for a side/hobby project.

Totally makes sense! I was just curious your overall thinking. Again, this is all really great work!

> Personally (and everyone is going to see this different), I think ColorPicker is best left to 3rd party libs. Not everyone needs one, and there are many different styles that this control can take (WinUI version, WinUI Com. Toolkit, my version, every other colorpicker in existence). 

Yes, everyone has their viewpoint. Personally, the fact that there are so many color pickers in existence is exactly why this all needs to be standardized. We all need to stop re-inventing the wheel and standardize. My plan for Avalonia is to use the UWP community toolkit version. There is hope that WinUI will adopt this updated style in the future as well. At least doing this we aren't creating a new variation other than what is required for Avalonia-specific styles and object model.

I also realize we are stepping into a 4th class of controls. Controls that aren't really well suited to be 'lookless.' Meaning they are not easily re-stylable (without copy/pasting the entire template) and have a lot of named parts in a tightly controlled configuration and are highly specialized. NavigationView is in the same category. However, these are so convenient the benefits in development speed outweigh any downsides in my mind.

> The biggest difference I see, is I decided to let the icons draw themselves, rather than make them like WinUI where elements (TextBlock, Path, etc.) are injected into the tree.

That's a good idea. @maxkatz6 That's a bit like what was discussed for FontIcon to get the export working to native menus.

> Go for it. Split/ToggleSplit Button I did use some custom internal stuff to implement this. Basically I have a very basic VisualStateManager to help with switching all the different states (this is one area where the CSS style styling in Avalonia doesn't work as nicely). You'll have to remove that, but otherwise feel free to use it as a starting point.

Thanks! I'll use your implementation as a base along with the WinUI code/styles.

**Comment by maxkatz6** [comment]
> That's a good idea. @maxkatz6 That's a bit like what was discussed for FontIcon to get the export working to native menus.

Controls rendering in Avalonia is not that big deal, and it can be done with templated icons. The bigger difference in these approaches is performance, that should be better with @amwx approach, and customizability, that is better with my approach. Considering controls build-in the framework, I would prefer second approach if possible.
Coming back to the native menus and rendering to a bitmap, I don't know whole picture of this problem, but it seems to be related to a question, how to manage lifetime of the bitmap rendered from control.

**Comment by maxkatz6** [comment]
> ColorPicker (however I plan a port that is closer to WinUI + UWP Community Toolkit)

> Personally (and everyone is going to see this different), I think ColorPicker is best left to 3rd party libs.

> We all need to stop re-inventing the wheel and standardize. My plan for Avalonia is to use the UWP community toolkit version.

A bit of background:
Speaking about "4th class controls" there is no clear decision, how to integrate them into Avalonia/core, and should we even do it.
Avalonia has bad experience with DataGrid control, that is highly complex, has a lot of non-standard implementations (i.e. it has its own scrolling/virtualization, its own bindings parsing), that made this control very hard to maintain as well. Still there is no doubt that this control is highly popular as well and we can't just throw it away. Porting more complex controls from WPF/UWP we don't want to repeat the history and make the same mistake.

ColorPicker, on other hand, is not that relatively complex, and we might potentially use this control in Avalonia DevTools project, where it will be pretty much welcomed. However it will be hard to convince core team, that it should be part of Avalonia. Other options are to keep this control in Avalonia org, but outside of main repo, or create some kind of Avalonia Community Toolkit @AvaloniaCommunity might be interested in latest, but I don't have contacts with them. Side note, both options will make ColorPicker harder to use in DevTools project, which is part of main repo.

And about WinUI implementation, I agree, that one in WCT has better styles now, and we are not required to strictly follow WinUI styles or even API.
Also it's way better to have implementation that renders to the drawing context directly instead of creating and filling in-memory byte array and creating an bitmap from it. Just like @amwx [did it in this repo](https://github.com/amwx/FluentAvalonia/blob/306b532480e758eaf40ab44b1c8d3aabbdd38ec5/FluentAvalonia/UI/Controls/ColorPicker/ColorSpectrum.cs#L498-L542), but it shouldn't be hardcoded to only one Skia implementation, at least if we consider this control as part of Avalonia.

**Comment by amwx** [comment]
> Yes, everyone has their viewpoint. Personally, the fact that there are so many color pickers in existence is exactly why this all needs to be standardized. We all need to stop re-inventing the wheel and standardize. 

That is a valid point but design preferences vary by individual, so standardization isn't necessarily always a good thing. I much prefer the community toolkit version over the UWP/WinUI version (which I believe you did, right?) which is why I took some design from that. But, I guess have a standard as a starting point would be a good idea, which can be fitted & customized as needed.

> I also realize we are stepping into a 4th class of controls. Controls that aren't really well suited to be 'lookless.' Meaning they are not easily re-stylable (without copy/pasting the entire template) and have a lot of named parts in a tightly controlled configuration and are highly specialized. NavigationView is in the same category. However, these are so convenient the benefits in development speed outweigh any downsides in my mind.

That's where things like the lightweight styling comes in handy too. Some controls are too complex where heavy modification is not ideal, but still allows more common things to be customized.

**Comment by amwx** [comment]
> Also it's way better to have implementation that renders to the drawing context directly instead of creating and filling in-memory byte array and creating an bitmap from it. Just like @amwx [did it in this repo](https://github.com/amwx/FluentAvalonia/blob/306b532480e758eaf40ab44b1c8d3aabbdd38ec5/FluentAvalonia/UI/Controls/ColorPicker/ColorSpectrum.cs#L498-L542), but it shouldn't be hardcoded to only one Skia implementation, at least if we consider this control as part of Avalonia.

The color palette/box spectrum (whatever you want to call it) is drawn by filling in a byte array and could be done with any backend. It's not ideal and I've added as much optimization to keep it from needing to re-render unless necessary. IIRC, MS draws and keeps 6 bitmaps alive adjusting the opacity of each? I opted for the needs more power, but uses less memory approach.
And it's only locked to Skia because Direct2D only has Linear and Radial Gradients, where Skia has the sweep gradient too and the ColorWheel is possible without also needing a bitmap approach. It's probably possible in Direct2D using a custom shader or something, but that's above my knowledge level.  The ColorTriangle I implemented requires some bitmap effects that probably could be done in Direct2D, but since you have to basically create a new image for each effect in Direct2D it's a pain. Skia is just easy

**Comment by robloo** [comment]
@maxkatz6 

> The bigger difference in these approaches is performance, that should be better with @amwx approach, and customizability, that is better with my approach. Considering controls build-in the framework, I would prefer second approach if possible.

Fair enough, I don't have much of a concern either way. Something like a font icon or bitmap doesn't seem like there is anything to customize but I could be wrong. I was just thinking it would make rasterization simple as well but don't understand the internals that well to comment on it.

> there is no clear decision, how to integrate them into Avalonia/core, and should we even do it.

Well, the decision has kind-of already been made, at least a precident. The DataGrid is a perfect example. Everyone expects it in toolkits these days so unfortunately it just has to be maintained. I had no idea it was parsing it's own bindings... Also, unfortunately, the WPF version wasn't open sourced at the time and the silverlight code always had a lot more issues. Comparatively speaking a ColorPicker is far easier as you said and so is a NavigationView. While I agree pulling in this class of controls must be done carefully I think these are the safest to include. I know the core team is under a huge maintenance burden now as the framework is still quite new. However, it will get better. Code does stabilize.

> Also it's way better to have implementation that renders to the drawing context directly instead of creating and filling in-memory byte array and creating an bitmap from it.

This is a good idea; however, you already pointed out one of the main reasons to avoid it. There is no low-level API in Avalonia that can render a spectrum. You have to fall back into Direct2D or Skia. That is a worse design -- having to maintain two rendering backends in the control itself. In addition, a WriteableBitmap approach uses pre-existing WinUI code which shortens development time. This is something that can definitely change in the future, but I don't think a more direct rendering approach should be taken for the initial implementation.

@amwx 

> I much prefer the community toolkit version over the UWP/WinUI version (which I believe you did, right?) which is why I took some design from that. But, I guess have a standard as a starting point would be a good idea, which can be fitted & customized as needed.

Yes, after Microsoft seemed unwilling to improve the WinUI version I wrote the WCT version as an alternative. Of course there were a lot of great ideas from the community in the design process. I'm trying to standardize this control across all XAML toolkits because I think it's important for both developers and users. Of course I'm biased but it sounds like we are all receptive to using the WCT design.

> That's where things like the lightweight styling comes in handy too. Some controls are too complex where heavy modification is not ideal, but still allows more common things to be customized.

That's a great point and it's what is done in most cases for WinUI now. The only downside is there are a lot of undocumented named resources to play around with now. There doesn't seem to be a better solution though.

> The color palette/box spectrum (whatever you want to call it) is drawn by filling in a byte array and could be done with any backend. It's not ideal and I've added as much optimization to keep it from needing to re-render unless necessary. IIRC, MS draws and keeps 6 bitmaps alive adjusting the opacity of each? 

As mentioned I would want to keep the WinUI implementation to start. This can be adjusted if Avalonia ever completes a composition-type backend abstraction over Skia and Direct2D.

A triangle shape is a good idea too like in some other graphics software. It should be possible to add this in in the future by just adding a new spectrum shape enum and code paths. I don't think it would be a huge tear-up but you would know more.
