### ISSUE TITLE
Have an option for automatically adjusting when system theme or accent color changes

### ISSUE THREAD

**Issue by PhantomGamers** [amwx/FluentAvalonia#148]
**Is your feature request related to a problem? Please describe.**
Currently when a theme is not explicitly set, FluentAvalonia will default to the system theme and accent color on Windows 11 (and 10 maybe?), but if the system theme is changed while the application is running it will not be reflected in the application.

**Describe the solution you'd like**
Fluent apps, at least the ones included in Windows 11, will adjust to system theme and accent color changes even while the apps are already running. There should be an option included in FluentAvalonia to enable this behavior.

**Additional context**
I believe this can be accomplished by subscribing to the [SystemEvents.UserPreferenceChanged event](https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.systemevents.userpreferencechanged). I was planning on testing this in my own app but I am unable to until #145 is solved.

**Comment by amwx** [comment]
I've purposely left this up to users to handle, which is why `InvalidateThemingFromSystemThemeChanged()` exists. It may be a bit more work on users end, but gives you control for how to handle it whether using `SystemEvents` class or handling it from the WndProc directly. Also, `Microsoft.Win32.SystemEvents` isn't available on netstandard2.x which makes that unsuitable for use within FluentAvalonia.
