### ISSUE TITLE
TabView: reordering tabs doesn't work properly if CanDragTabs=true

### ISSUE THREAD

**Issue by manfromarce** [amwx/FluentAvalonia#149]
**Describe the bug**
When CanDragTabs is true, tabs seem to go back to their original position after being reordered. 
In addition, it would be nice if the drag animation was the same, because when CanDragTabs = true it doesn't preview the tab being dragged and displays a forbidden symbol which is a bit confusing.

**Screenshots**
CanDragTabs = true:
![1](https://user-images.githubusercontent.com/45036600/170860994-4b132277-df02-404c-af9d-955de8b6d6dc.gif)

CanDragTabs = false:
![2](https://user-images.githubusercontent.com/45036600/170860996-5d112cc6-5103-4e8f-ac8b-7db1db64aa5d.gif)

**Desktop/Platform (please complete the following information):**
 - OS: Windows 10
 - FluentAvalonia Version: latest
 - Avalonia Version: latest

**Comment by amwx** [comment]
There are some issues with the DragDrop APIs in Avalonia which gave me trouble when I was porting TabView, one of which is that pointer notifications seem to be suppressed when in a drag-drop operation, which is why dragging doesn't have the preview popup. The "no drop" icon shows because you drag outside the tab strip which sets the allowed drag effects to 'None' as unless you handle `TabDroppedOutside` event it's invalid to drop a tab there. 

There does appear to be a bug here with reordering not committing when drag-drop is enabled which needs investigation. As I said, the drag-drop stuff is finicky, so I have to be careful here.
