### ISSUE TITLE
Cannot remove ListBoxItem margin

### ISSUE THREAD

**Issue by mysteryx93** [amwx/FluentAvalonia#176]
I'm trying to override the ListBoxItem margin; but it's impossible because it's hardcoded instead of being set via style. My only option would be to replace the ContentPresenter altogether.

https://github.com/amwx/FluentAvalonia/blob/master/FluentAvalonia/Styling/BasicControls/ListBoxStyles.axaml#L76

**Comment by mysteryx93** [comment]
There's the same issue with ComboBoxItem

Here's another one. RadioButton is hardcoded with a height of 32 that cannot be overriden.
https://github.com/amwx/FluentAvalonia/blob/master/FluentAvalonia/Styling/BasicControls/RadioButtonStyles.axaml#L42

**Comment by amwx** [comment]
Apologies for the delay in response - These types of styling issues should be fixable once I get stuff updated to v2/Avalonia 11.0 since that should've fixed the local value in template priority issue. My goal is to get a preview package out in early September. For now in the stable 1.x package, you'll have to replace the entire template to override that resource.
