### ISSUE TITLE
Core Window System Decorations is not supported or broken

### ISSUE THREAD

**Issue by zlnimda** [amwx/FluentAvalonia#181]
**Describe the bug**
There is multiple bugs when system decorations is set to `None` with `CoreWindow` class at least on Win10.
The border is showed with a large band, size of the window is ignored, resizing the window is completely broken.

**Screenshots**
![image](https://user-images.githubusercontent.com/4094642/184202191-056ea2bb-14d4-4334-9145-2f20f2601d97.png)

**Desktop/Platform (please complete the following information):**
 - OS: **Windows 10**
 - FluentAvalonia Version: **1.4.1**
 - Avalonia Version: **0.10.17**

**Comment by amwx** [comment]
`CoreWindow` doesn't support messing with the system decorations by design. It has custom logic to do its own thing for rendering the titlebar and resizing areas so its closer to a UWP app which doesn't work with other custom window frame stuff. Use a normal Avalonia `Window` if you want control over this stuff.
