### ISSUE TITLE
Core Window Style Error on Windows

### ISSUE THREAD

**Issue by Dynesshely** [amwx/FluentAvalonia#184]
**Describe the bug**
In System scale -> 125%

**Screenshots**
![image](https://user-images.githubusercontent.com/50760269/185535127-fe20168e-3179-42b4-bff6-303f2e98f662.png)

**Desktop/Platform (please complete the following information):**
 - OS: Windows 11 21H2 22000.856
 - FluentAvalonia Version: latest
 - Avalonia Version: latest

**Comment by amwx** [comment]
Don't set the `TransparencyLevelHint` property to `Transparent`, (or don't use CoreWindow if you must have a transparent window). When the window is set to Transparent, DWM still draws the system caption bar at the top of the window - and the way Avalonia Win32 & WinUI composition is set up there is no way to stop that from happening - which is why you're seeing the duplicate glyphs (its the system and my custom caption buttons, which aren't perfectly aligned)

**Comment by Dynesshely** [comment]
Tnx
