### ISSUE TITLE
AccentColor customization?

### ISSUE THREAD

**Issue by nlogozzo** [amwx/FluentAvalonia#19]
By default the accent color on Windows is blue and on Linux it's a purple-ish color. Is there a way we can change the accent color used throughout the application?

**Comment by amwx** [comment]
By default, Windows is pulling the accent color from the system, and OSX/linux it falls back to SlateBlue since there's not really a set accent color outside of windows (at least on linux, no idea about osx) - so that's why you're getting different colors.
As for overriding - you're *supposed* to be able to, but after testing this apparently you can't. I know why this is, I just need to find a solution - so thanks for bringing this up!

**Comment by nlogozzo** [comment]
Sounds good! I'd love to see an option with `var theme = AvaloniaLocator.Current.GetService<FluentAvaloniaTheme>();` to maybe do `theme.RequestedAccentColor = "Red"` or something like that

**Comment by amwx** [comment]
Custom accent color implemented in v1.1.1
