### ISSUE TITLE
[Feature Request] Update TabView

### ISSUE THREAD

**Issue by nlogozzo** [amwx/FluentAvalonia#22]
Microsoft with new WinUI has created a new `TabView` that replaces `TabControl` (https://docs.microsoft.com/en-us/windows/apps/design/controls/tab-view) The old `TabControl` is known as a `Pivot` (https://docs.microsoft.com/en-us/windows/apps/design/controls/pivot)
Could we see these updated controls in this library?

**Comment by amwx** [comment]
I wouldn't necessarily say it's a replacement for `TabControl`/`Pivot` since it's a heavier weight, top-level navigation focused control - and why so many complained when MS tried to drop the `Pivot` control. I will look into adding it though as there is value to it, but no timeline for it

**Comment by nlogozzo** [comment]
No worry about the timeline, I like the current TabControl/Pivot navigation...however the TabView would be helpful for some future projects

**Comment by nlogozzo** [comment]
Any update on this? @amwx

**Comment by amwx** [comment]
Its on my list of things to add after v1.2, which I'm working on right now - that is taking longer than I'd like because it's required reworking some things. v1.2 will be out sometime in December, so probably early next year time frame wise for the TabView. The good news is TabView is open sourced so it should be relatively easy, and I've peeked at the source code and some of the stuff I'm currently working on may be needed for the TabView, so it sets itself up nicely.

**Comment by nlogozzo** [comment]
Sounds good! Thanks!!
