### ISSUE TITLE
ContentDialog does not map DefaultButton

### ISSUE THREAD

**Issue by stevemonaco** [amwx/FluentAvalonia#225]
**Describe the bug**
When assigning to `ContentDialog.DefaultButton`, it should be expected that the specified button receives `IsDefault="True"`. I assume it to be a missed propagation in `ContentDialog`. This breaks the ability to use the Enter key to ok/confirm a dialog.

**Repro for later screenshot**
Start with FluentAvaloniaSamples and change the [ContentDialogPageViewModel](https://github.com/amwx/FluentAvalonia/blob/master/FluentAvaloniaSamples/ViewModels/SamplePages/ContentDialogPageViewModel.cs#L112) so that it has:

```cs
DefaultButton = ContentDialogButton.Primary
```

Run app, open dialog, press enter, and no action will be taken.

In the debug tools, set `IsDefault` to `True` for the primary button and Enter works. The escape key already works as-is.

**Screenshots**
![ContentDialogDefault](https://user-images.githubusercontent.com/1782158/198864988-18368f20-baf8-47c5-b6e8-63f6795a0ac5.png)

**Desktop/Platform (please complete the following information):**
 - Win10
 - FluentAvalonia latest
 - Avalonia 11preview2

**Additional context**
I first produced in my own app (11preview2) while building a more MVVM-friendly wrapper. It's a bit complex and I'm unfamiliar with `ContentDialog`, so I reproduced in the sample.

**Comment by amwx** [comment]
Yep this seems to be a bug. IIRC I didn't use `IsDefault` or `IsCancel` because I thought they also close the window after invoking which isn't desirable since ContentDialog is overlaid and not in its own Window - though it doesn't do this so I'm not sure where I got that from (maybe WPF or Winforms behavior?).  Anyway, I also thought I at least handled this in a key up or down handler - which after just checking I don't. Will add this to the list to fix though

More as a note to myself - I believe this is the same for TaskDialog.

**Comment by stevemonaco** [comment]
Thanks for investigating. I'm not tied to `IsDefault`, a key handler for Enter will do fine, too.
