### ISSUE TITLE
Exception thrown: 'System.MissingMethodException' in FluentAvalonia.dll

### ISSUE THREAD

**Issue by saibot75** [amwx/FluentAvalonia#237]
When calling ShowAsync on a ContentDialog I get the following exception in 2.0.0-preview3.

Exception thrown: 'System.MissingMethodException' in FluentAvalonia.dll
An unhandled exception of type 'System.MissingMethodException' occurred in FluentAvalonia.dll
Method not found: 'Void Avalonia.Media.TextFormatting.TextLayout..ctor(System.String, Avalonia.Media.Typeface, Double, Avalonia.Media.IBrush, 
Avalonia.Media.TextAlignment, Avalonia.Media.TextWrapping, Avalonia.Media.TextTrimming, Avalonia.Media.TextDecorationCollection, 
Avalonia.Media.FlowDirection, Double, Double, Double, Int32, 
System.Collections.Generic.IReadOnlyList`1<Avalonia.Utilities.ValueSpan`1<Avalonia.Media.TextFormatting.TextRunProperties>>)'.

Code example that worked in 1.4.4:
var td = new ContentDialog()
{
Title = "Welcome",
PrimaryButtonText = "Log in",
SecondaryButtonText = "Cancel",
IsPrimaryButtonEnabled = true,
IsSecondaryButtonEnabled = true,
PrimaryButtonCommand = viewModel.LoginCommand,
Content = viewModel				
};

var result = await td.ShowAsync();

Am I missing setting up something for 2.0.0-preview3? I got FluentAvalonia.UI.Windowing and also tried adding UseFAWindowing() but it's still same error.

**Comment by saibot75** [comment]
For info. This is most probably due to very recent change in Avalonia.Media.TextFormatting.TextLayout constructor. An extra parameter, double letterSpacing = 0 was added.

**Comment by amwx** [comment]
Are you using one of the nightly Avalonia builds? If so, that's probably why. The kearning PR wasn't merged until after Avalonia 11-preview3 was released and I don't have a nightly feed that keeps up with the in-between changes


> I got FluentAvalonia.UI.Windowing and also tried adding UseFAWindowing() but it's still same error.

Just a note, that's only required for TaskDialog. ContentDialog works entirely independent of Windowing since its only an overlay dialog.

**Comment by saibot75** [comment]
> Are you using one of the nightly Avalonia builds? If so, that's probably why. The kearning PR wasn't merged until after Avalonia 11-preview3 was released and I don't have a nightly feed that keeps up with the in-between changes
> 

Yes, I used a nightly build.

> > I got FluentAvalonia.UI.Windowing and also tried adding UseFAWindowing() but it's still same error.
> 
> Just a note, that's only required for TaskDialog. ContentDialog works entirely independent of Windowing since its only an overlay dialog.

Ah, I missed that.

**Comment by amwx** [comment]
Normally FA versions should be relatively stable between Avalonia versions since they maintain a stable ABI, but given we're in previews where breaking changes can occur, this can be expected. If you want to use a nightly, you'll have to clone this repo and manually adjust the package references to the nightly build
