### ISSUE TITLE
Standardize to IconSource over (FA)IconElement

### ISSUE THREAD

**Issue by amwx** [amwx/FluentAvalonia#255]
Currently WinUI (and FA) have a mix of controls that expect either an FAIconElement or an IconSource, but neither has been standardized. Newer WinUI controls are usually using IconSource and that's what I've used in the new controls (SettingsExpander and TaskDialog) in this library since they have the ability to declared as resources and reused, whereas IconElements are controls and can only exist in one place at a time.

Of the WinUI stuff ported:
IconElement
- NavigationViewItem
- FAMenuFlyout items
- CommandBarButton/ToggleButton

IconSource
- TabViewItem
- InfoBar
- InfoBadge
- TeachingTip

Personally, I'd like to standardize all controls to use IconSources, but I'm interested in feedback for this change. Doing this would standardize the NavigationView and FAMenuFlyout to the newer controls and leverage the features of IconSources, but would be an API change from upstream WinUI. This would also involve a name change for the properties, i.e., `Icon` would become `IconSource` which is the standard property name in other controls.

Note that if this change is made, this will be a hard breaking change for v2. I may leave the existing properties as obsolete (but non-functional) for the remainder of the previews, though.

**Comment by robloo** [comment]
Porting from WinUI to Avalonia + FluentAvalonia requires quite a few breaking changes already. I have given up original plans to maintain the code side-by-side. Therefore, I think changes like this -- especially to improve things -- are always justified. The goal of this project should be more to support WinUI features and control functionality, not maintain API compatibility.

The problem is if a feature or code pattern simply isn't available in Avalonia. That requires reworking things as you know which is time consuming. This seems like a simple renaming which is just fine from my viewpoint.

**Comment by TheXamlGuy** [comment]
Happy to see this changed to use IconSource across all controls 👍

**Comment by robloo** [comment]
@amwx 

Just to be sure, the way to switch current code over to this is basically rename `Icon` -> `IconSource` and replace your icon controls i.e. `FontIcon` -> `FontIconSource`, correct?

I guess for some reason I didn't think it was needed to change `FontIcon` because there would be a common IIconSource or something so you could still use `FontIcon` with newer code (backwards compatible). Surprised Microsoft didn't use an interface instead of concrete types honestly.

**Comment by robloo** [comment]
It's really useful to declare icons as resources to centralize them. That's proving to be a great simplification (outweighing breaking-change work) and makes switching icons a lot more streamlined in the future (although a script exists to do that in XAML).
