### ISSUE TITLE
NumericUpDown is not displaying the up/down button icons.

### ISSUE THREAD

**Issue by renrutsirhc** [amwx/FluentAvalonia#259]
**Describe the bug**
NumericUpDown is not displaying the up/down button icons correctly when using the FluentAvaloniaTheme

**Screenshots**
![image](https://user-images.githubusercontent.com/12220071/208289689-157ef1b4-6423-4a81-8450-62f99b63808f.png)

**Desktop/Platform (please complete the following information):**
 - OS: [e.g. Windows (11/10), linux (distro), osx, wasm, etc] Win 10
 - FluentAvalonia Version [e.g. 1.0.0, or latest] 1.45
 - Avalonia Version [e.g. 0.10.10] 0.10.18

**Additional context**
If I additionally include  <FluentTheme Mode="Light" /> in app.xaml, these do appear - but then other styles are messed up!

**Comment by amwx** [comment]
Can't reproduce. Have you altered/customized anything that may have changed the font or glyph. The 'unknown glyph' character tells me the button isn't finding the symbol font (`SymbolThemeFontFamily` resource). Check in dev tools that the repeat button's FontFamily is still correct. 
![image](https://user-images.githubusercontent.com/40413319/208322182-80820bb3-e1fb-493f-8c70-de4922b3185d.png)

Otherwise I'll likely need a minimal repro of this.

**Comment by renrutsirhc** [comment]
Ah thanks for the hint @amwx! It turns out I had a style setter for TextBlock changing the FontFamily to Segoe UI that was overriding the font for the TextBlock inside the repeat button. Removing this, fixed the problem!
