### ISSUE TITLE
Add smooth animations to controls like Expander or ComboBox

### ISSUE THREAD

**Issue by onionware-github** [amwx/FluentAvalonia#273]
When you use controls from FluentAvalonia and compare them to UWP/WinUI 3, you recognize that there are no smooth animations in FluentAvalonia when you expand an Expander or a ComboBox. It would be nice, when this functionality could be added to FluentAvalonia too to make apps smoother in terms of user experience.

**Comment by amwx** [comment]
For Expander: There's some complications in the way this control works. Technically there is animation (`ContentTransition` property) but it applies to the ContentPresenter only, not the container the ContentPresenter is placed in - that's has its visibility bound to the `IsExpanded` property so it appears immediately. Properly animating this would require calculations in the expander code upstream (WinUI has template settings for the animation values) so fixing this is out of my hands. @robloo you've worked on the Expander recently, tagging to see if you have any thoughts on this. 


As for anything that requires a popup, this just isn't possible. Support for this would have to start upstream in Avalonia in the popup positioning API:
- In order to properly animate, the actual popup window would have to be slightly bigger than the popup to allow for proper transforms to not get cut off. This then needs to get factored into the popup placement logic so that the popup still appears in the correct location. (this is what UWP/WinUI does)
- However, Avalonia has to support a host of different platforms and some don't support transparency. I don't necessarily think everything needs to brought to the lowest common denominator, but that is a point that has to be handled in Avalonia. And the Wayland compositor for linux has a very restrictive windowing API that would also probably not help this.
- Also, on Windows, you'd pretty much lose the ability to apply acrylic blur to popups. Even with WinUI comp enabled in Avalonia, we're still outside the WinUI compositor, so effects like acrylic and mica are applied directly to the window surface, unlike WinUI where they can get a composition brush with the effect and apply it anywhere. In Avalonia, if you tried to animate a popup with acrylic blur enabled, you'd see the blurred window as the content animates. I don't know if there's a way to get the effect bitmap from DWM that could be passed into Avalonia's rendering stack to get around this. Even if you could, 1) it is obviously only solving the problem for Windows, and 2) would likely be a very expensive operation (DWM -> DirectX texture -> OpenGL -> Skia)

I'd love to get animations (and shadows for popups) working as they're a big part of the fluent design system, but my hands are tied by what Avalonia can do (and to no fault of the Avalonia team either) based on the limits of the OSs.

**Comment by robloo** [comment]
This fell off my radar. If the proposal is to follow WinUI upstream with template settings to help smoth animations that perhaps is a good idea. Will definitely be willing to help with implementing any changes but I don't have a lot of experience animating with Avalonia yet and this low priority to me. If @onionware-github wants to take lead on changes I support.
