### ISSUE TITLE
PathIcon dont showing inside of Button or ListBoxItem

### ISSUE THREAD

**Issue by alex6dj** [amwx/FluentAvalonia#280]
**Describe the bug**
Switching themes for testing, and appears a problem with the visibility of PathIcon in FluentAvalonia. In Avalonia.Fluent theme shows correctly, but not in FluentAvalonia. Tested inside a Button an a ListBoxItem. Using DevTools the PathIcon don even show. Using ListBoxItem I can check PathIcon is there after selecting in DevTools but in the interface is transparent. Changing Background and Foreground dont have any effect. Any workaround is welcome.

**Screenshots**
![Captura de pantalla (30)](https://user-images.githubusercontent.com/27690651/215484574-fb410832-6502-429d-8cda-f41af336325f.png)
![Captura de pantalla (31)](https://user-images.githubusercontent.com/27690651/215484579-e9087dd8-5b80-4e37-bdda-e65403ff7c4b.png)

**Expected behaviour**
![Captura de pantalla (32)](https://user-images.githubusercontent.com/27690651/215486837-f5bc3a22-36e5-406f-b27f-450a005079f9.png)

**Desktop/Platform (please complete the following information):**
 - OS: Windows 10
 - FluentAvalonia Version 2.0.0-preview4
 - Avalonia Version 11-preview4

**Additional context**

**Comment by timunie** [comment]
FluentAvalonia has it's own `PathIcon`. I think it was renamed to `FAPathIcon` now in order to be distinct from Avalonia. If you want to render Avalonias PathIcons, you have to add a Style on your own. The original can be found here: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Fluent/Controls/PathIcon.xaml

@amwx do you want to add support for this control? If so, I can open a PR where I copy over the Style linked above.

**Comment by alex6dj** [comment]
You are right just tested before even read this comment. But I was trying to stick with the base `PathIcon` because this way I dont have to do any code change. Any way, the other thing stopping the use of this library was a performance problem I had with `ItemPresenter` some time ago and this already go away then I think is a good time to make a migration. I really like the hard work done in this. Feel free to close this issue if will stick with the internal `FAPathIcon`.

**Comment by amwx** [comment]
> @amwx do you want to add support for this control? If so, I can open a PR where I copy over the Style linked above.

Because I have an alternative, let's leave it for now, but if demand grows for it then we can do that in the future. 

@alex6dj 
I'm not sure how FA was leading to perf issues with ItemsPresenter, but ItemsControls should be getting better in preview5 after that refactor. Also, if perf is an issue, you could looking into using `IconSource` over `FAIconElement`. The idea there is similar to flyouts where you can declare the icon once and use it everywhere, which is probably really useful for your case of using them in an ItemsControl, ex:

```Xaml
<UserControl.Resources>
    <ui:PathIconSource x:Key="DeleteIcon" Data="M..." />
</UserControl.Resources>

<!-- Usage -->
<Button>
    <ui:IconSourceElement IconSource="{StaticResource DeleteIcon}" />
</Button>
```

Will also move to discussion as this may be useful to others
