### ISSUE TITLE
Add Open(File | Folder)Dialog as well SaveFileDialog

### ISSUE THREAD

**Issue by KluDev** [amwx/FluentAvalonia#289]
It would nice to have FluentAvalonia support for those dialogs as well.

**Comment by robloo** [comment]
What do you mean here?

 1. Avalonia upstream has a managed file dialog. Do you mean FluentAvalonia should provide control themes for this?
 2. Avalonia also allows just using the standard, native file dialogs in a platform-abstracted way. Since this is integrating with the device almost always you should use this method. In this case FluentAvalonia doesn't need to do anything.

**Comment by amwx** [comment]
The managed file dialog ControlTheme in the 11.0/FA2.0 stuff already, there were no styles for it in the 0.10.x/FA1.x stuff. 

The native system dialogs are already implemented upstream and are out of scope for this library (they're also system dialogs so there's nothing I could do anyway).
