### ISSUE TITLE
Datagrid checkbox styling

### ISSUE THREAD

**Issue by vmiwouter** [amwx/FluentAvalonia#311]
When you add a checkbox to the column it seems to be a fixed width size.
So if you make it smaller it falls behind:
![image](https://user-images.githubusercontent.com/44747792/221235962-14172210-641e-45ed-af8f-ac65e45d58da.png)
![image](https://user-images.githubusercontent.com/44747792/221236047-d5dbffbe-c998-48c3-ae09-00119b4e4b73.png)

**Comment by timunie** [comment]
I think the root cause it that line: https://github.com/amwx/FluentAvalonia/blob/8636ee6ed41420ea93b93a1b6011999768330f83/src/FluentAvalonia/Styling/ControlThemes/BasicControls/CheckBoxStyles.axaml#L20

I see three solutions: 
1. Remove the `MinWidth` from `CheckBox` completely
2. Add a special `Style` for `CheckBoxes` inside a `DataGridCell`
3. Override the given resource in `DataGrid`-style

@amwx any preference?

**Comment by amwx** [comment]
I've decided to just go ahead and remove the forced MinWidth from `CheckBox`, `RadioButton`, and `ToggleSwitch`. Changes are already in the open next preview PR.

**Comment by timunie** [comment]
@amwx great, thank you a bunch as always!
