### ISSUE TITLE
ContentDialog is not using the passed datacontext

### ISSUE THREAD

**Issue by trrahul** [amwx/FluentAvalonia#393]
**Describe the bug**
```
public async void ShowInputDialogAsync()
{
    var dialog = new ContentDialog()
    {
        Title = "My Dialog Title",
        PrimaryButtonText = "Ok",
        SecondaryButtonText = "Not OK",
        CloseButtonText = "Close"
    };

    // Pass the dialog if you need to hide it from the ViewModel.
    var viewModel = new MyViewModel(dialog);

    // In our case the Content is a UserControl, but can be anything.
    dialog.Content = new ContentDialogInputExample()
    {
        DataContext = viewModel
    };

    var result = await dialog.ShowAsync();
}
```
At runtime ContentDialogInputExample's datacontext is not MyViewModel. So the following kind of code does not work.

```
public class MyViewModel : ReactiveObject
{
    private readonly ContentDialog _dialog;
    private string? _itemName;
    private bool _showError;

    public MyViewModel(ContentDialog dialog)
    {
        _dialog = dialog;
        _dialog.PrimaryButtonCommand = ReactiveCommand.Create(() => { },
            this.WhenAnyValue(x => x.ItemName, x => !string.IsNullOrWhiteSpace(x)));
        this.WhenAnyValue(x => x.ItemName).Subscribe(x => { ShowError = string.IsNullOrWhiteSpace(x); });
    }
    

    public bool ShowError
    {
        get => _showError;
        set => this.RaiseAndSetIfChanged(ref _showError, value);
    }

    public string? ItemName
    {
        get => _itemName;
        set => this.RaiseAndSetIfChanged(ref _itemName, value);
    }

}

```

**Desktop/Platform (please complete the following information):**
 - OS: Windows 10
 - FluentAvalonia 2.0.0-rc1
 - Avalonia Version 11.0.0-rc1.1

**Additional context**

**Comment by amwx** [comment]
That's because nothing is setting the DataContext on the ContentDialog, its being set on the UserControl content. I can't set the DataContext on the ContentDialog in the initialization code because of how dialogs are implemented in case it causes other issues with binding and DataTemplates (like it accidentally overriding an already supplied DataContext). To do what you want, you need to explicitly set the DataContext on the ContentDialog to your ViewModel. It should also work if you set the content to your ViewModel and use a DataTemplate to construct the actual view since IIRC Content on a ContentControl sets the DataContext if its not a Control, but that's not how this sample (in the demo app) was set up (this one was community provided).
