### ISSUE TITLE
DropDownButton and SplitButton seem broken in FluentAvaloniaSamples/FAControlsGallery

### ISSUE THREAD

**Issue by Leon99** [amwx/FluentAvalonia#397]
Pressing the arrow doesn't do anything

**Comment by amwx** [comment]
IIRC these examples don't have a flyout assigned to them so there is no dropdown content to show. Note that controls inherited from Avalonia don't have complex demos here because I only apply Fluent v2 styling to them. Avalonia's sample stuff should be used for functionality of these controls. Not including a flyout thought was probably an oversight when these controls were removed here and added upstream in Avalonia, and I do think would be a good addition.

**Comment by robloo** [comment]
@amwx you mean you would add an empty flyout to the default control theme in Avalonia? I'll check WinUI and see what that does.

**Comment by amwx** [comment]
@robloo No, I mean the samples in the demo app should have a flyout attached so that at least if you click it, something appears and it doesn't look broken.

**Comment by robloo** [comment]
Note DropDownButton is broken a few different ways right now:

 * Disabled styling is completely incorrect
 * Pointer-over and press styling doesn't work

**Comment by robloo** [comment]
Opened a PR to fix all issues here
