### ISSUE TITLE
[Android] Dark mode not detected

### ISSUE THREAD

**Issue by nlogozzo** [amwx/FluentAvalonia#454]
**Describe the bug**
On desktop (Linux and Windows), FluentAvalonia correctly detects and applies dark mode on app startup if that's my system them.
On android (Samsung s22, dark mode enabled), it stays in light mode. (Unless I manually switch FluentAvalonia's theme to dark), meaning it doesn't detect system dark mode correctly. 

**Desktop/Platform (please complete the following information):**
 - OS: Android 13/OneUI 5.1
 - FluentAvalonia Version: 2.0.1
 - Avalonia Version: 11.0.2

**Comment by amwx** [comment]
On Android (and really every OS now), system settings are taken from Avalonia's `IPlatformSettings` API. If its not working, its most likely because your device/OS is not supported by whatever method Avalonia uses to get them, as there are restrictions. You'll have to find the related PR upstream for more on that.

**Comment by nlogozzo** [comment]
> On Android (and really every OS now), system settings are taken from Avalonia's `IPlatformSettings` API. If its not working, its most likely because your device/OS is not supported by whatever method Avalonia uses to get them, as there are restrictions. You'll have to find the related PR upstream for more on that.

Ah good to know...thanks :)
