### ISSUE TITLE
Improve expander animations

### ISSUE THREAD

**Issue by styris-ame** [amwx/FluentAvalonia#521]
**Is your feature request related to a problem? Please describe.**
See the following FluentAvalonia animation:

![FAControlsGallery Desktop_PId8vbRKNE](https://github.com/amwx/FluentAvalonia/assets/123859041/073aa9b5-b4a4-4c2c-b230-57da8414ce40)

It looks okay, however not as nice as the settings app animation:

![ApplicationFrameHost_RVrHmYgHVc](https://github.com/amwx/FluentAvalonia/assets/123859041/dcbdfbab-e3be-4509-b249-43a8cd997b67)

**Describe the solution you'd like**
Updated animations to more closely match the settings app.

**Comment by amwx** [comment]
It was an intentional decision not to include the animation within SettingsExpander. Because of the way Avalonia implemented the animation of the actual expander control, it doesn't work quite right in all situations with this control (particularly if you want the implicit composition animations to make the rest of the UI move with the expansion/collapse).

You can still enable it yourself with a Selector that targets the `Expander` in the template of the `SettingsExpander` to set the ContentTransition property.

**Comment by styris-ame** [comment]
@amwx Thanks for the reply! If I may ask, is there an Avalonia issue to track this as an issue, or is it inherent to the design?

**Comment by saeed-neorelm** [comment]
> It was an intentional decision not to include the animation within SettingsExpander. Because of the way Avalonia implemented the animation of the actual expander control, it doesn't work quite right in all situations with this control (particularly if you want the implicit composition animations to make the rest of the UI move with the expansion/collapse).
> 
> You can still enable it yourself with a Selector that targets the `Expander` in the template of the `SettingsExpander` to set the ContentTransition property.

can this be an option in the package? I found it too difficult to implement myself, there's alpha masking and then the close animation needs to be adjusted, overall not really easy to do
