### ISSUE TITLE
[Demo | Idea] add syntax highlight and copy support to the code examples

### ISSUE THREAD

**Issue by timunie** [amwx/FluentAvalonia#55]
Hi @amwx 

I like the demo app very much as it is really helpful 👍 . While playing around I was wondering if syntax highlighting and copy-support would be good. 

I tried out some things and found that AvaloniaEdit might be helpful: 

![image](https://user-images.githubusercontent.com/47110241/141768125-17c6054d-7eb2-4712-a5b9-bd1fd7ed0c23.png)

See: https://github.com/AvaloniaUI/AvaloniaEdit

I have a branch for this here: https://github.com/timunie/FluentAvalonia/tree/feature/ImproveDemoApp

If you like this idea I can work on the branch more and send a PR.

Happy coding
Tim

**Comment by amwx** [comment]
I actually am planning an overhaul to the sample app for the v1.2 update, part of which will address the syntax highlighting - copy support is an interesting idea and one I hadn't thought of, however, so that's added to the list. In terms of syntax highlighting, I haven't ruled anything out but I'm kind of hesitant to require the full dependency of AvaloniaEdit. I'm also toying with using github markdown style approach to things (primarily so I don't have to hack things together from an XML or json file as is done now).

I'm working on v1.2 stuff, which will add a couple new controls and begin adding unit tests as the primary focus. Once I get that done, I'll look much more into how I want to redo the sample app (and best approach).

**Comment by amwx** [comment]
The new sample app included with v1.2 now uses AvaloniaEdit to provide syntax highlighting to code samples, and also includes the ability copy.

**Comment by timunie** [comment]
Woah I had a look at the new Demo, and it is... I don't have words for it, ... it is just stunning. Also the resources page is soooo helpful, I think this will be my new goto-tool :-) 

🙏 Thank you mate 🙏 

Happy coding
Tim
