### ISSUE TITLE
TabView border disappears when there is a single tab only

### ISSUE THREAD

**Issue by cricketthomas** [amwx/FluentAvalonia#552]
**Describe the bug**
When using the TabView component, the border to the right of the tab disappears if there is just one item in the TabView list. Not sure if this is intentional or not, it can easily be styled. That being said, the right border arc does disappear when the tab is empty.

```     
<Style Selector="ui|TabView /template/ ContentPresenter">
      <Setter Property="BorderBrush">
          <Setter.Value>
              <SolidColorBrush Opacity="1" Color="{DynamicResource TabViewBorderBrush}" />
          </Setter.Value>
      </Setter>
      <Setter Property="BorderThickness" Value="0,0,0,1" />
  </Style>
```
Border visible on multiple tabs:
![image](https://github.com/amwx/FluentAvalonia/assets/15821271/ac42d32c-29bf-4b7b-9139-e42dc5d66e3c)

Border gone when there's a single tabview item:

![image](https://github.com/amwx/FluentAvalonia/assets/15821271/13fa99ab-dfd9-45e9-a7df-bc989011dbd2)

**Desktop/Platform:**
 - OS: Windows 11
 - FluentAvalonia Version 2.1.0 and current
 - Avalonia Version  11.1.0-beta1

**Comment by amwx** [comment]
Definitely a bug, probably missing a resource somewhere.
WinUI: 
![image](https://github.com/amwx/FluentAvalonia/assets/40413319/b9bd264c-9ba0-4941-b228-a999fd50a6f9)

**Comment by cricketthomas** [comment]
It also seems to be the same with front of the tab missing the border if you add margin to the front of the tabs or  whitespace with `TabStripHeader="       "`. 
I've been trying to fix it in the source, but I am really new to Avalonia. 
![image](https://github.com/amwx/FluentAvalonia/assets/15821271/5055aaf1-fb97-4a2e-899a-914441cb77c6)

**Comment by amwx** [comment]
Issue has been fixed*

![image](https://github.com/amwx/FluentAvalonia/assets/40413319/3c4fd9b7-07af-476a-aceb-48aaa77b7785)

Two issues:
1- Avalonia for some reason won't render a 1px height Border, so that wasn't even rendering. Rectangle works fine, so these elements were changed to that (which may even be a perf benefit).
2- Avalonia's ItemsPresenter doesn't support `Header` and `Footer` like WinUI does, and so I ignored them. Turns out its kind of needed to fill some gaps, so I've docked the ItemsPresenter in a DockPanel. This shouldn't cause any issues now as this is essentially the same thing as WinUI and TabView doesn't support virtualization right now anyway.

Fix is now in the 2.1 branch

**Comment by robloo** [comment]
> Avalonia for some reason won't render a 1px height Border, so that wasn't even rendering. Rectangle works fine, so these elements were changed to that (which may even be a perf benefit).

Hm, hope I didn't break that. Will keep an eye on it.

**Comment by cricketthomas** [comment]
Thank you for the fix!
Quick question, the border left seems to be different color FA than it is on WinUI but only on dark mode? It's the most unimportant thing but i just noticed it between dark mode and light mode. It almost seems like a WinUi quirk too where the border at the top is slightly lighter than the sides. I am still looking for the resource to style and I can open a PR when I find it (if acceptable or appropriate). 
 
FluentAvaloniaUI 2.1.0-preview2
![image](https://github.com/amwx/FluentAvalonia/assets/15821271/583d8b8b-99c7-471e-8229-18765b9e1b3a)
 
 WinUI

![image](https://github.com/amwx/FluentAvalonia/assets/15821271/5c71e772-6918-4848-9178-1e16889d9714)
