### ISSUE TITLE
Support Bottom NavigationView

### ISSUE THREAD

**Issue by fulco813** [amwx/FluentAvalonia#570]
May I ask if FluentAvalonia will support bottom NavigationView like this?

![image](https://github.com/amwx/FluentAvalonia/assets/67252536/0f0adac4-b4e9-417a-8408-aa8872330462)

**Comment by Tryanks** [comment]
Could you provide information on what this control looks like under Fluent Design v2? In WinUI 3.0, this control does not exist by default; in common practices (such as in Windows 11), I have not seen any use cases for it.

**Comment by fulco813** [comment]
This is a control in Android, I'm sorry, maybe I misunderstood, is FluentAvalonia not going to support mobile UI?

**Comment by Tryanks** [comment]
FA certainly supports any target platform that Avalonia can provide. To clarify, my statement does not represent any official viewpoint of this library, and I apologize for any confusion.

If you want to provide a NavigationView located at the bottom, since there is no baseline solution that provides the style of this control under Fluent Design, developers must try to design it themselves.

In my opinion, this is not the goal of this library: it aims to replicate WinUI 3.0 but does not overly provide additional components.

Therefore, I believe that for this control, we should try to find its standard implementation version or provide a third-party component `FluentAvalonia.BottomNaviView` (just like `FluentAvalonia.ProgressingRing`).

**Comment by fulco813** [comment]
Thanks for your explanation, then I have to write some custom styles based on TabControl.
I will close this issue
