### ISSUE TITLE
[Feature Request] Watermark Animation

### ISSUE THREAD

**Issue by Maruhl** [amwx/FluentAvalonia#60]
I know that FluentAvalonia follows the WinUI design pattern, but would it still be possible to make an animation like in Material Design?

Material Design Watermark:
![Material Design Watermark](https://user-images.githubusercontent.com/41585619/146499111-b1a88762-d8db-4496-a101-25e2d499f5c9.gif)

Source:
[Material.Avalonia](https://github.com/AvaloniaCommunity/material.avalonia)

**Comment by nlogozzo** [comment]
I'm sure it is possible, however as you said yourself, it's part of material design and not WinUI (which this repo is for). Therefore, I would use Material.Avalonia and not this library if you are trying to achieve material design

**Comment by amwx** [comment]
This isn't something to add to the core library since it isn't a Fluent design thing, but it should be relatively easy to make work by modifying the Styles for `TextBox`. You could probably copy and paste the selectors that perform this animation directly from Material.Avalonia (just make sure any named elements are correct). I'm not sure how well this will look since Fluent design has a border around the textbox and material design doesn't, but that's not for me to judge.

**Comment by Maruhl** [comment]
@nlogozzo 
I use already Material.Avalonia, but i would like to switch to FluentAvalonia.
I realize that this is a completely different design. My main concern is that I have input masks that visually take up less space than if you place a label in front of it.
Also, this is in my eyes pointless more code.

@amwx 
Yes, the border is definitely an argument. Maybe I should think more about how to prepare it visually - or go more into FluentAvalonia design.
