### ISSUE TITLE
Icons too little

### ISSUE THREAD

**Issue by hepe00** [amwx/FluentAvalonia#619]
Can add more icon to Symbol ? That was too little icons now when i wanted info,Tablet,TileDown etc,.

Thank you for your hard work.

**Comment by amwx** [comment]
The Symbol enum is not meant to be all-encompassing. There are other icons in the font file that used - though I don't know if the other ones you are listing are included (you'd have to test with their unicode value). The font only gets updated if absolutely necessary, since its kind of a pain to generate.
