### ISSUE TITLE
Wrong Font Family name for Windows build 22000

### ISSUE THREAD

**Issue by emmauss** [amwx/FluentAvalonia#65]
The font family of the default font released in windows 11 is `Segoe UI Variable` and not `Segoe UI Variable Text`. This prevents non avalonia controls that try to use the same font to fail if it picks the font family from the window class.

**Comment by amwx** [comment]
`Segoe UI Variable` is the general name for the font, but it's actually 3 different font sets `Segoe UI Variable Text`, `Segoe UI Variable Display`, and `Segoe UI Variable Small`. If you set the FontFamily to just `Segoe UI Variable`, it's not recognized and Skia falls back to regular `Segoe UI` 
Demo: (Segoe UI is drawn in red, Segoe UI Variable & variants are drawn in white), notice how using `Segoe UI Variable` is exactly the same as Segoe UI

![image](https://user-images.githubusercontent.com/40413319/147794345-2f36494d-e0b0-4cd1-a730-6a3180e82bf5.png)

I chose the Text variant because I don't actually know which one Windows and WinUI use, and Text seemed appropriate and the three variants generally look the same anyway. MS docs explain when you should use each variant, but nothing in WinUI explains which one `ContentControlThemeFontFamily` maps to, or even if they have a way of dynamically changing it.

**Comment by emmauss** [comment]
I see. Then it's a difference in how fonts are loaded between libraries. We use sixlabors to load fonts for our custom control, which uses the font family name, and not the variant name. We'll just use the family name for windows 11 on our app.
