### ISSUE TITLE
NavigationView is empty if MenuItems not loaded in CTOR

### ISSUE THREAD

**Issue by kvalitetskontrollMarkaryd** [amwx/FluentAvalonia#8]
Great job you have done! Love it!

MenuItems are loaded according to the other Issue i filed. Thanks for the help with that!.

The problem is that if I load them with a "Initialized += MainWindow_Loaded;" event, there are no items showing up in the NavigationView. Only if I load them directly in the constructor.

This is working, even if sometimes the last Item does not show any Content until clicking back and forward on the items.
`public MainViewModel(INavigationLookupDataService navigationLookupDataService)
        {
            _navigationLookupDataService = navigationLookupDataService;

            MenuItems = new ObservableCollection<LookupItem>();
            
            LoadNavigationLookupAsync();
        }`

This is not working, no MenuItems are showing up:
`public MainWindow()
        {
            var container = ((App)Application.Current).Container;
            ViewModel = (MainViewModel?) ActivatorUtilities.GetServiceOrCreateInstance(container, typeof(MainViewModel));
            Initialized += MainWindow_Loaded;
            AvaloniaXamlLoader.Load(this);
#if DEBUG
            this.AttachDevTools();
#endif
        }

        private async void MainWindow_Loaded(object? sender, EventArgs e)
        {
            await ViewModel.LoadAsync();
        }`

`public MainViewModel(INavigationLookupDataService navigationLookupDataService)
        {
            _navigationLookupDataService = navigationLookupDataService;

            MenuItems = new ObservableCollection<LookupItem>();
            
            //LoadNavigationLookupAsync();
        }
        
        public async Task LoadAsync()
        {
            await LoadNavigationLookupAsync(); // Fires, I have checked!
        }`

**Comment by amwx** [comment]
I'm finishing up a major update to the library, and the NavView is the last thing on my list, but I'll add this to my list to take a look at, and I should get to it this week.

**Comment by amwx** [comment]
Ok had a look at this. What I think is happening is your `DataContext` is being set twice. The `Initialized` event is called before the constructor finishes, and I'm assuming you set the `DataContext` in the constructor to your `ViewModel` property. If you look at `OnFrameworkInitializationCompleted()` in `App.xaml.cs` (I'm assuming you're using the MVVM project template?) the `DataContext` should be set as part of the MainWindow creation via object initializer, which means the `DataContext` is being reset to a blank instance, which is why you're not seeing anything show up.

If you remove setting the `DataContext` in `App.xaml.cs`, all should work again (I was able to repro and this fixed it)

**Comment by kvalitetskontrollMarkaryd** [comment]
You are absolutely right. Thanks for your help!
