### ISSUE TITLE
Menu Styles

### ISSUE THREAD

**Issue by nlogozzo** [amwx/FluentAvalonia#82]
FluentAvalonia seems to have bigger menu padding compared to WinUI. 

Here is the menu in Paint:
![image](https://user-images.githubusercontent.com/17648453/150869090-7050e7c9-5147-40ab-bcd1-a72cd770082b.png)

And here is the menu in FluentAvalonia:
![image](https://user-images.githubusercontent.com/17648453/150869188-de41173c-9631-4c93-a15b-44ea286a1f0d.png)

The height of the MenuItem seems to be larger in FluentAvalonia than in WinUI

**Comment by robloo** [comment]
I didn't realize they update MSPaint with WinUI3, interesting. Keep in mind WinUI3 source code isn't published yet and there may be some changes to the default styles compared to the public WinUI2. I doubt Microsoft has kept them perfectly in sync. Otherwise, the MSPaint app may have customized it.

Bottom line though: I would take a look at the default styles on the WinUI2 github and compare them to the ones in this repository. If the padding/margin is the same this isn't really an issue and should be closed IMO.

**Comment by amwx** [comment]
They're updating a lot of the Win32 apps to look more modern. Even notepad, which is still in the insider preview of windows, looks gorgeous in the new design.

I don't know if the menu items themselves are too big, I need to look at that, but I noticed even before this issue there is too much padding at the top/bottom menus that's needs sorting out. It's on my list of things to look at. The WinUI 2 XamlControlsGallery and the WinUI sample app (MUXControlsTestApp) are what I use for reference w/ the Live Visual Tree to inspect if something doesn't look right or I'm reverse engineering

**Comment by amwx** [comment]
Fixed and included in v1.2

![image](https://user-images.githubusercontent.com/40413319/152280370-314ab16b-8bcf-4524-b18c-f177e03e7e0b.png)
