### ISSUE TITLE
[TabView] AddItem + Resize window => InvalidDataException

### ISSUE THREAD

**Issue by fmaeseele** [amwx/FluentAvalonia#97]
Hi,

While playing with the new Sample application and TabView, if you click on the "+" Icon to add a new tab and then you resize the window of the application, it crashes with an InvalidDataException: Invalid double value
The issue appears in TabViewItem.cs: 264
            TabViewTemplateSettings.TabGeometry = StreamGeometry.Parse(builder.ToString());

Nice feature by the way 👍 
François

**Comment by amwx** [comment]
I haven't been able to repro this but I did find another issue on one of the TabView examples in trying to. Which example on the TabView page was it, and what OS?

**Comment by fmaeseele** [comment]
1st example. 
OS is Windows 10 21H2 (Latest version)

**Comment by amwx** [comment]
Still unable to repro on Win 11, Win 10, or linux and testing each TabView sample. Closing issue

**Comment by amwx** [comment]
I still cannot repro this issue. I have tried every TabView sample in the sample app page and resized trying to get it to break. The stack trace reveals it is in parsing of the TabViewItem geometry, based on the "Invalid double value", I'm guessing somehow double.NaN is getting calculated somewhere. 

Can you produce step-by-step instructions on what you're doing to make this happen? Or even a video of it happening might be helpful.

**Comment by wihrl** [comment]
Just run this demo and resize the window. That's all it takes.
I'm using Windows 11 with 2 screens (125% scaling) if that's relevant.

![image](https://user-images.githubusercontent.com/57505542/166099936-40ba36df-d12e-49d6-b750-ec41e207ee98.png)

**Comment by amwx** [comment]
I still cannot get this to crash. The only issue when resizing the window is flickering, but that's out of my hands as I believe its related to the ListBox calling BringIntoView on the selected item (WinUI has the same issue), but it never crashes. I've tried using higher scaling, adding/removing tabs from each of the examples, and all is fine.

Can you throw a Debug.WriteLine in on TabViewItem.UpdateTabGeometry (where the error is occuring) to print out the result of the string builder there? Since StreamGeometry.Parse is encountering an invalid double, knowing which value is wrong might give me a bit of insight or at the very least I can hack in a fail-safe there as a temporary fix until I can get the crash to repro.

**Comment by wihrl** [comment]
`F1 M0,32  a 4,4 0 0 0 4,-4  L 4,8  a 8,8 0 0 1 8,-8  l 165,6,0  a 8,8 0 0 1 8,8  l 0,20  a 4,4 0 0 0 4,4 Z`

**Comment by manfromarce** [comment]
This also happens to me when adding more than 4-5 tabs (without touching the window). It throws "Invalid double value"

**Comment by amwx** [comment]
Ok, I think I've figured out why this is happening and why I can't repro it. The data from wihrl looks fine on first glance, until you look at it in detail and see the part `l 165,6,0` is what's causing this to fail because... 
When compiling the path data, `StringBuilder` uses the current culture to format the doubles, but Avalonia's path markup parser uses invariant culture. I'm `en-US` which uses `.` for decimals (which is why I can't get it to crash no matter what), while y'all are using cultures that use `,` instead - thus StringBuilder is outputting `165,6` instead of the expected `165.6` for parsing - which is causing the crash. Changing my culture to non-en-US and turning off `UseLayoutRounding` I finally got this to crash, and forcing InvariantCulture in the StringBuilder does fix it, PR coming shortly
